# Generated by Django 4.1.3 on 2022-12-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=15)),
                ('destino', models.CharField(max_length=15)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
