# Generated by Django 4.1.3 on 2023-01-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaster', '__first__'),
        ('AppMessages', '0002_msg_delete_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='userto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMaster.usuario'),
        ),
    ]
