# Generated by Django 4.1.3 on 2023-01-19 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppMessages', '0004_alter_msg_userto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='userto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
